"""create monitoring tables

Revision ID: 359e33f1fd17
Revises: 0001_create_users_table
Create Date: 2026-08-30 19:14:34.862156

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0002_create_monitoring_tables"
down_revision: str | None = '0001_create_users_table'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('method', sa.String(length=10), server_default=sa.text("'GET'"), nullable=False),
    sa.Column('expected_status', sa.Integer(), server_default=sa.text('200'), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('check_interval_seconds', sa.Integer(), server_default=sa.text('300'), nullable=False),
    sa.Column('max_down_alerts', sa.Integer(), server_default=sa.text('4'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('alert_emails', postgresql.ARRAY(sa.String(length=255)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.Enum('unknown', 'up', 'down', name='website_status'), server_default=sa.text("'unknown'::website_status"), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('down_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('down_alerts_sent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_websites_last_checked_at'), 'websites', ['last_checked_at'], unique=False)
    op.create_index(op.f('ix_websites_status'), 'websites', ['status'], unique=False)
    op.create_table('website_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_up', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_checks_checked_at'), 'website_checks', ['checked_at'], unique=False)
    op.create_index('ix_website_checks_site_time', 'website_checks', ['website_id', sa.literal_column('checked_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_website_checks_site_time', table_name='website_checks')
    op.drop_index(op.f('ix_website_checks_checked_at'), table_name='website_checks')
    op.drop_table('website_checks')
    op.drop_index(op.f('ix_websites_status'), table_name='websites')
    op.drop_index(op.f('ix_websites_last_checked_at'), table_name='websites')
    op.drop_table('websites')
    # Alembic does not drop enum types it implicitly created.
    sa.Enum(name='website_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
